# Uncomment the next line to define a global platform for your project


platform :ios, '9.0'

target 'TabbarProject' do
use_frameworks!

end
  # Pods for TabbarProject

  target 'TabbarProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SBTUITestTunnel/Server', :configuration => ['Debug']
  end

  target 'TabbarProjectUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SBTUITestTunnel/Client'
  end
